### PR TITLE
MM-24585: Add swagger specification for push proxy API

### PR DESCRIPTION
**Pull request by agnivade**
- Added the OpenAPI 3.0 schema file.
- Also added helper commands to build and serve the schema UI using
swagger-validate and redoc-cli.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-24585

### CODE REVIEW

**Comment by agnivade** [comment]
pp

**Comment by enahum** [comment]
Is it possible to add a description to each body parameter?

Should we add examples of supported notification types.

Finally can we move this to a doc directory or something like that?

**Comment by agnivade** [comment]
> Is it possible to add a description to each body parameter?

Sure, will do.

> Should we add examples of supported notification types.

It is already there. Unless I am misunderstanding something.

> Finally can we move this to a doc directory or something like that?

I have placed it in swagger directory. Happy to rename it to doc if you prefer.

**Comment by enahum** [comment]
Nope, swagger dir is fine, I miss that cause of package.json living in the root folder.

**Comment by agnivade** [comment]
@enahum - updated

**Comment by agnivade** [comment]
Going to merge this as this is just documentation.

**Pull request merged**
