### PR TITLE
Add golangci-lint to the codebase

### PR DESCRIPTION
**Pull request by agnivade**
Add golangci-lint to the codebase

#### Ticket link

https://mattermost.atlassian.net/browse/MM-24317

### CODE REVIEW

**Comment by agnivade** [comment]
@metanerd - This is failing due to not able to write to /usr/local/bin. But the server repo passes. Anything I need to add to let it write to /usr/local/bin ?

**Comment by metanerd** [comment]
> @metanerd - This is failing due to not able to write to /usr/local/bin. But the server repo passes. Anything I need to add to let it write to /usr/local/bin ?

It probably requires the customized build image we use for the mattermost-server repo: https://github.com/mattermost/mattermost-server/blob/a6a58f99e7292e1d298a3c47c39994ec642878b6/.circleci/config.yml#L145

So two options:
1. use same build image as server uses
1. use own build image for push proxy

https://github.com/mattermost/mattermost-server/blob/master/build/Dockerfile.buildenv
this is the build Dockerfile. I think we could reuse the server one. It doesn't have a huge impact down the road.

**Comment by agnivade** [comment]
@srkgupta - This needs some real testing compared to https://github.com/mattermost/mattermost-push-proxy/pull/63.

**Pull request merged**
