### PR TITLE
Added AckID to log message

### PR DESCRIPTION
**Pull request by icelander**
#### Summary

Now logging the AckID to help diagnose issues sending push notifications.

Signed-off-by: Paul Rothrock <paul@movetoiceland.com>

### CODE REVIEW

**Comment by jasonblais** [comment]
@enahum Any privacy concerns with sending an `AckId` via the logs?

**Review by enahum — APPROVED** [review]
@jasonblais no worries about using the ackId

**Comment by hanzei** [comment]
@icelander Can we merge this?

**Comment by icelander** [comment]
@hanzei Yep!

**Pull request merged**
